### ISSUE TITLE
Install instructions

### ISSUE THREAD

**Issue by 1j01** [ActivityWatch/aw-watcher-vscode#11]
It would be nice to mention on the readme how you can install from the extensions panel in VS Code, or from [VS Code Marketplace](https://marketplace.visualstudio.com/items?itemName=lindraupe.aw-watcher-vscode)

**Comment by Otto-AA** [comment]
Do you mean the installation of ActivityWatch or the installation of the Extension?

**Comment by ErikBjare** [comment]
@Otto-AA Pretty sure he means the extension.

**Comment by TemaSM** [comment]
Any updates here?

**Comment by ErikBjare** [comment]
Nope, waiting for someone to submit a PR :)

**Comment by bryanwills** [comment]
I would like to know how to install Modules for ActivityWatch. I have been trying to figure it out for the last 30 minutes and haven't gotten anywhere. Any help on this is appreciated. I am on Mac OS Big Sur.

**Comment by johan-bjareholt** [comment]
Solved in #24, closing
