### ISSUE TITLE
Does not work using Remote - WSL (and presumably the other VSCode Remote variants)

### ISSUE THREAD

**Issue by flaw** [ActivityWatch/aw-watcher-vscode#17]
This is already brushed upon over at #9, but I don't quite agree that it's purely a VSCode issue so I figured I'd create this to keep track of the work if we can figure out an easy fix.

The root of the problem is that the extension tires to connect to "localhost:5600", which works rather poorly when the extension is running on the remote extension host.
Luckily for us, an extension can choose on which extension host (local or remote) it runs on by specifying an `extensionKind` attribute in package.json, see https://code.visualstudio.com/api/advanced-topics/remote-extensions#incorrect-execution-location
So simply updating package.json and repackaging should take care of that. 

I went ahead and used the `remote.extensionKind` configuration entry to force the extension to run on the UI side by adding 
```
    "remote.extensionKind": {
        "lindraupe.aw-watcher-vscode": ["ui"]
    }
```
to user settings.json and ended up with the following:

![image](https://user-images.githubusercontent.com/386551/100013653-d933b900-2ddd-11eb-9387-b63b5ed58218.png)

As you can see it's already pretty promising, the only thing not working seemingly being the project entry.

I took a look at how `_getProjectFolder()` is implemented and my first guess is trying to pass a remote file Uri to `workspace.getWorkspaceFolder()` doesn't quite work in this case, so some alternative way of figuring out how we determine the project would be needed. 
Perhaps one option could be to simply use `workspace.name`? As far as I can gather that'll return the name of the currently open folder, or `undefined` if we only have single files open. I'm unsure if that's sufficient from AW perspective or not.

For now I wasn't able to actually get the development environment running to test any code changes so the `workspace.name` solution is just guesswork, but I can try that again when I have some more time.

**Comment by johan-bjareholt** [comment]
> The root of the problem is that the extension tires to connect to "localhost:5600", which works rather poorly when the extension is running on the remote extension host.
> Luckily for us, an extension can choose on which extension host (local or remote) it runs on by specifying an extensionKind attribute in package.json, see https://code.visualstudio.com/api/advanced-topics/remote-extensions#incorrect-execution-location
> So simply updating package.json and repackaging should take care of that.

That's a great find, would love to see a PR for this!

> I took a look at how _getProjectFolder() is implemented and my first guess is trying to pass a remote file Uri to workspace.getWorkspaceFolder() doesn't quite work in this case, so some alternative way of figuring out how we determine the project would be needed.
Perhaps one option could be to simply use workspace.name? As far as I can gather that'll return the name of the currently open folder, or undefined if we only have single files open. I'm unsure if that's sufficient from AW perspective or not.

To see what's expected for editor events to contain, take a look at this

https://docs.activitywatch.net/en/latest/buckets-and-events.html#app-editor-activity

It's supposed to provide a full path to the project, so it's not perfect to just use the workspace.name. You should however not set it to undefined, that might break the web-ui (not sure, but possibly).
One option would be to use getWorkspaceFolder when not on remote files and just have something like "/workspacename" on remote files as a workaround, better than not working at all at least.

**Comment by flaw** [comment]
I'll try at some point again if I can get the extension development tooling working so I could actually try some potential solutions. If/when I manage to set up something that I can actually test with I'll see about making a PR.
