### ISSUE TITLE
watcher not running

### ISSUE THREAD

**Issue by LucaPizzagalli** [ActivityWatch/aw-watcher-vscode#2]
Hello,
I have a aw-server running, and all seems working fine.
I have then installed the extension in vscode but in the aw web ui under "editor" i find nothing.
I'm using ubuntu 16.

**Comment by Otto-AA** [comment]
Can you check if (1) there is a bucket for vscode in the webui at _Raw Data_ and (2) if there is data in this bucket?

**Comment by LucaPizzagalli** [comment]
(1) yes
(2) yes

but under Editor > bucket > select editor watcher bucket   it says "no editor buckets available"

**Comment by johan-bjareholt** [comment]
v0.8 beta 6 broke editor visualization sadly, beta 5 should work fine or beta 7 once that releases (a fix is done, but we have not made a new build since).

If you are using beta 6 and my assumption is correct you should see this message:

> Request error undefined. See F12 console for more info.

**Comment by LucaPizzagalli** [comment]
yes, I'm using v0.8.0b6 (the vscode watcher is at version 0.32).
I can't find any "Request error undefined. See F12 console for more info." but anyway I will wait for beta 7 then!
good work guys!

**Comment by johan-bjareholt** [comment]
@devzsolt Works fine for me with aw-watcher-vim so it shouldn't be something related to aw-server or the webui but rather this watcher most likely. If you go into "Raw Data" and press on aw-watcher-vscode does it say "Type: app.editor.activity" or something else? The only requirement for the "Editor" tab to show the bucket is that the bucket should have the app.editor.activity type.

**Comment by devzsolt** [comment]
@johan-bjareholt in Raw Data the bucket shows `Type: coding.vscode`
Then probably this is what's wrong, right?

**Comment by devzsolt** [comment]
Update: fixed things in my local copy and looks like the only big problem was the wrong bucket type. Thanks for the cue @johan-bjareholt 
So if someone could update the official release in vscode marketplace that would be usueful for others.

**Comment by johan-bjareholt** [comment]
@devzsolt Oh, I thought that @Otto-AA had already made that move but unfortunately not.
Only @Otto-AA has access to the plugin in Microsoft marketplace so unfortunately I can't fix that.

**Comment by ErikBjare** [comment]
@Otto-AA could you add @devzsolt as a contributor to the plugin?

**Comment by johan-bjareholt** [comment]
@Otto-AA created a publisher on microsoft marketplace and added me, I have now uploaded the last version and seems to work for me now!

Closing this, feel free to comment here if it still doesn't work for someone and I'll re-open it.
