### ISSUE TITLE
Who owns the publisher on VS marketplace?

### ISSUE THREAD

**Issue by ErikBjare** [ActivityWatch/aw-watcher-vscode#20]
I noticed the extension slug had a weird username in it that I didn't recognize (https://marketplace.visualstudio.com/items?itemName=lindraupe.aw-watcher-vscode), and when I clicked it to get to the publisher I got a page that seemed very official: https://marketplace.visualstudio.com/publishers/lindraupe

However, I certainly don't have access to it, and I doubt @johan-bjareholt has either? I guess it might be @Otto-AA, which would be fair enough, but I'd like to know if that's the case or not.

**Comment by johan-bjareholt** [comment]
I have access. The VS Marketplace admin pages are incredibly confusing though so I'm having a hard time finding how to access it and invite you.

The name lindraupe.aw-watcher-vscode has that name due to legacy, I remember we had a discussion about it a long time ago and decided to keep that name for some reason.

**Comment by ErikBjare** [comment]
Cool, just checking.

**Comment by Otto-AA** [comment]
> I guess it might be @Otto-AA, which would be fair enough, but I'd like to know if that's the case or not.

Yes, that name is from me. I didn't check my access rights to it lately, but if I still have some I would be glad to hand it over. If you want to just ping me

**Comment by tippf3hlr** [comment]
When searching for `activitywatch` in the vscode marketplace, two extensions with no visible difference show up, but the legacy `lindraupe.aw-watcher-vscode` is `v0.4.1` while the other is `v0.5.0`. If the legacy should be kept, it would be probably good to mark it as such? (and flagged with @deprecated)

**Comment by ErikBjare** [comment]
I checked and can only access the new one, so @Otto-AA would need to fix/deprecate the old one.

If @Otto-AA wants to add me as a developer on the old listing, so I can edit it and do the necessary changes myself, my VSCode marketplace user ID is: ba8c4799-9ba5-4d16-a6c1-a6441f7d8035

**Comment by Otto-AA** [comment]
Nevermind, now you should also have access @ErikBjare

**Comment by johan-bjareholt** [comment]
I wrote a request to deprecate the old at "lindraupe.aw-watcher-vscode" to be replaced with the new "activitywatch.aw-watcher-vscode": https://github.com/microsoft/vscode-discussions/discussions/1#discussioncomment-4684336

> I checked and can only access the new one, so @Otto-AA would need to fix/deprecate the old one.

I just checked my own account, seems like I have the opposite issue and only have access to the old one actually!

**Comment by ErikBjare** [comment]
@johan-bjareholt I need your user ID to add you

**Comment by johan-bjareholt** [comment]
@ErikBjare My user id is 5dae5896-b278-6d4f-860c-12cf436de9bb
