### ISSUE TITLE
Couldn't create Bucket on WSL2

### ISSUE THREAD

**Issue by unlimish** [ActivityWatch/aw-watcher-vscode#21]
I installed ActivityWatch to Windows, but the extension running on WSL2 ubuntu tries to create Bucket to the not exist ActivityWatch on Ubuntu, then it shows the error message below.

> [ActivityWatch] Couldn't create Bucket. Please make sure the server is running properly and then run the [Reload ActivityWatch] command.

**Comment by johan-bjareholt** [comment]
This is not an activitywatch issue, WSL2 is a virtual machine which makes it impossible to talk with the host system unless specifically allowed to (which you need to configure yourself, I'm not experienced with WSL though so I don't know how).

An alternative which should work would be to install vscode on windows, install the extension there and then also install vscode in WSL and then use the vscode remote development feature to connect to it. Support for this was recently added to aw-watcher-vscode https://github.com/ActivityWatch/aw-watcher-vscode/pull/18. The version in vscode marketplace is not yet updated however, so you'd need to run the extension from source until that is fixed.

Good luck!
