### ISSUE TITLE
Duration is always zero

### ISSUE THREAD

**Issue by devzsolt** [ActivityWatch/aw-watcher-vscode#3]
Seems like all the logged events have `"duration": 0.0` stored. Might be related to issue #2

versions:
-  AW 0.8.0 beta 7
- VSCode 1.29.1
- aw-watcher-vscode 0.3.2

**Comment by devzsolt** [comment]
It's not a bug but this is how heartbeats work.

**Comment by johan-bjareholt** [comment]
@devzsolt The client is allowed to send a 0-duration heartbeat, but once they are stored and merged in aw-server most heartbeats shall not have a 0-duration.
