### ISSUE TITLE
Hostname differs from the one detected by AW itself/other watchers

### ISSUE THREAD

**Issue by merlinschumacher** [ActivityWatch/aw-watcher-vscode#35]
Hi,

on my system this extension uses the Name "XY-Foobar" while AW itself and other extensions use "XY-FOOBAR" by default. Is there a way to override the hostname?

**Comment by johan-bjareholt** [comment]
@merlinschumacher Since you closed the issue, what was the solution?

**Comment by merlinschumacher** [comment]
Hey, I'm sorry. I just messed up, and this issue was meant for the Visual Studio extension, not the VSCode one.
