### ISSUE TITLE
Bug "Request error undefined" in ActivityWatch UI

### ISSUE THREAD

**Issue by gpassero** [ActivityWatch/aw-watcher-vscode#7]
I ran activitywatch-v0.8.0b6-windows-x86_64 and then opened VS Code v1.30.2 with the aw-watcher-vscode extension v0.4.0 enabled.

After that, I tried to access the ActivityWatch dashboard at http://localhost:5600/#/, tab `Activity`, and got this error:

![image](https://user-images.githubusercontent.com/4478523/52314224-eed1b780-2998-11e9-9017-4fd52c7a4806.png)

This error was displayed in the browser's console output:

```
Activity.vue:342 TypeError: Cannot read property 'duration' of undefined
    at a.<anonymous> (Activity.vue:413)
    at w (runtime.js:65)
    at Generator._invoke (runtime.js:299)
    at Generator.t.(:5600/anonymous function) [as next] (http://localhost:5600/static/js/0.eb46a9d79636be6aeb56.js:107:16480)
    at i (asyncToGenerator.js:17)
    at asyncToGenerator.js:28
```

Also, data is not loaded correctly at the Editor tab, as you can see in this print:

![image](https://user-images.githubusercontent.com/4478523/52314277-1d4f9280-2999-11e9-8cae-466752e7f075.png)

The extension doesn't seem to be compatible with activitywatch-v0.8.0b6. Has anyone tested it with activitywatch-v0.8.0b7?

**Comment by Otto-AA** [comment]
I wouldn't know, why the duration property shouldn't be set. Because the vscode extension always adds it with the value zero, and then the aw-server should merge them together, so it should be at least zero.

Could you look, if the events in your aw-watcher-vscode bucket (webui->raw data) have this property? Then we would know if the error is at storing the events or at displaying them and it would be easier to track it down :)

**Comment by gpassero** [comment]
I'm using Windows and unfortunately the release of activity watcher 0.8.0b7 for Windows is broken. :/

I'll wait for the fix in their branch. Thanks!

**Comment by johan-bjareholt** [comment]
Oh right, forgot about that.

We should hopefully have a new release soon!

**Comment by andypmw** [comment]
Hello,

I am using:

- Windows 10 64bit
- ActivityWatch v0.8.0b6
- Visual Studio Code

+1 for this GitHub issue... I guess I need to downgrade AW version at the moment...
